// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJwhQTHER9XjMuBQjWxeONlIkI43LGXps',
    appId: '1:749580264206:web:3f3124594cc0b17c1a2d5f',
    messagingSenderId: '749580264206',
    projectId: 'bright-weddings',
    authDomain: 'bright-weddings.firebaseapp.com',
    storageBucket: 'bright-weddings.appspot.com',
    measurementId: 'G-EVKVL5QE2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoPuLvcOfmQVGn_ovOEyqMMPG5fs643Ak',
    appId: '1:749580264206:android:d43ae1c3ece3fedb1a2d5f',
    messagingSenderId: '749580264206',
    projectId: 'bright-weddings',
    storageBucket: 'bright-weddings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcyggZVjH5Wx1-udRpLsGxwQJnsgC415w',
    appId: '1:749580264206:ios:0b49dc9e484eb6591a2d5f',
    messagingSenderId: '749580264206',
    projectId: 'bright-weddings',
    storageBucket: 'bright-weddings.appspot.com',
    iosBundleId: 'com.instagrp.matrimony.brightWeddings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJwhQTHER9XjMuBQjWxeONlIkI43LGXps',
    appId: '1:749580264206:web:959a8368d124cc4c1a2d5f',
    messagingSenderId: '749580264206',
    projectId: 'bright-weddings',
    authDomain: 'bright-weddings.firebaseapp.com',
    storageBucket: 'bright-weddings.appspot.com',
    measurementId: 'G-C6ZNK96M80',
  );
}
